version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/taskify
      - DB_NAME=taskify
      - JWT_SECRET=your-secret-key
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=3000
    depends_on:
      - mongodb
    restart: always
    networks:
      - taskify-network

  mongodb:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - taskify-network
    restart: always
    command: mongod --quiet --logpath /dev/null

networks:
  taskify-network:
    driver: bridge

volumes:
  mongodb_data:
